language: python

python:
  - '2.7'

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install codecov
  - pip install pytest-cov

script:
  - py.test --cov=aruudy/poetry tests/armetre_t.py

after_success:
  - codecov

deploy:
  provider: pypi
  user: kariminf
  password:
    secure: tuETKb7gU6x8CLMls5spFXmacdnD/cybXsF/tIWOo2jt5lU/rN9MjRfdJgBOd4PzNCPL7TXtgAc6GeoEBET13RL2dQswH183eRlI6Pl3Juc2AGw5a5RJurIt1Pfgd2OL4v22mIFcjy3Qeoj6QcAHYbkM6n3VXdu31kzg4nk0uut7hM/ucSMrr8RsdLzMACW8TCDoW3ogSNY+wLHOeYmkD9F5u906GByl8G+jyIg7Er/SK1Sul4jIaLfocQnUPv7q7GBhAgsKBKMLATlnhrrHliYBiaBJ6pg2me8WJuQSxeuMRBg7T+OVI0G/jrZ3kUBLWitzf9Y6kbQqdwyq174Vo+5uSoAzHWBUCrAn3giU6QztChHCwIG9uEAogfFu0LptCfiaVDYXhpWK/We/MbbsTuK+hg9s3gc7bzkcTLBBJzUxAA9zsLNCWxkOwXP97jRCHrOcmTnAIvwy/faOqEhsUDeqlz0tAXuPSpTAK2b99MSV3SbHhko+GGIvVXBYZQ5DMOOqTx/sxBcUWDXp+HQsK4PcxTTjAWc0L+5aTDUDrWKzxxtg3MeGrgCfeMa9oS0atzsDUQbTPhHgXHEo83LjfMCe8xAGACN7qM+n9CPY9IKJkwgU0TIHRZLC9gBjIC8+57j0v4F8XduFobXfjUgi6IA+kzE/9Lfrr/BwGZktJe4=
